fixtures:
  forge_modules:
    mount_core:
      repo: puppetlabs/mount_core
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
    stdlib:
      repo: puppetlabs/stdlib
    firewall:
      repo: puppetlabs/firewall
    mysql:
      repo: puppetlabs/mysql
    concat:
      repo: puppetlabs/concat
    augeasproviders_core:
      repo: puppet/augeasproviders_core
    augeasproviders_sysctl:
      repo: puppet/augeasproviders_sysctl
    logrotate:
      repo: puppet/logrotate
    epel:
      repo: puppet/epel
    limits:
      repo: saz/limits
    munge:
      repo: treydock/munge
    systemd:
      repo: puppet/systemd
    # Use git till released without legacy facts
    #rsyslog:
    #  repo: saz/rsyslog
    nhc:
      repo: treydock/nhc
    archive:
      repo: puppet/archive
    alternatives:
      repo: puppet/alternatives
    slurm_providers:
      repo: treydock/slurm_providers
  repositories:
    rsyslog:
      repo: https://github.com/saz/puppet-rsyslog.git
  symlinks:
    slurm: "#{source_dir}"
    site_slurm: "#{File.join(source_dir, 'spec/fixtures', 'site_slurm')}"
