---
.github/workflows/ci.yaml:
  acceptance_name: '${{ matrix.puppet }} ${{ matrix.set }} (slurm=${{ matrix.slurm_version }})'
  acceptance_matrix:
    set:
      - el8
      - el9
      - debian-11
      - debian-12
      - ubuntu-2204
      - ubuntu-2404
    puppet:
      - puppet8
    slurm_version:
      - '23.11.10'
      - '24.05.4'
  #acceptance_includes:
  #  - set: el8
  #    puppet: puppet7
  #    slurm_version: '24.05.4'
  #  - set: el9
  #    puppet: puppet7
  #    slurm_version: '24.05.4'
.gitlab-ci.yml:
  delete: true
.rubocop.yml:
  profiles:
    strict:
      configs:
        RSpec/MultipleMemoizedHelpers:
          Enabled: false
        RSpec/RepeatedExampleGroupBody:
          Enabled: false
appveyor.yml:
  delete: true
spec/acceptance/nodesets/el8.yml:
  unmanaged: true
  packages:
    - crontabs
spec/acceptance/nodesets/el9.yml:
  unmanaged: true
  packages:
    - crontabs
spec/acceptance/nodesets/el10.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-12.yml:
  unmanaged: true
  packages:
    - cron
    - iproute2
spec/acceptance/nodesets/ubuntu-2204.yml:
  unmanaged: true
  packages:
    - cron
spec/acceptance/nodesets/ubuntu-2404.yml:
  unmanaged: true
  packages:
    - cron
