---
.github/workflows/ci.yaml:
  acceptance_matrix:
    set:
      - centos-7
      - centos-8
      - debian-10
    puppet:
      - puppet6
      - puppet7
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/centos-6.yml:
  delete: true
spec/acceptance/nodesets/centos-7.yml:
  unmanaged: true
spec/acceptance/nodesets/centos-8.yml:
  unmanaged: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/debian-10.yml:
  unmanaged: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  delete: true
